/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rahul' at '12/5/16 4:32 PM' with Gradle 3.0
 *
 * @author rahul, @date 12/5/16 4:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
